on:
  push:
    tags:
    - '*'
name: docker-publish-tags

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: willnorris/imageproxy

    - uses: docker/build-push-action@v1
      with:
        context: .
        push: true
        tags: ${{ steps.meta.output.tags }}
        labels: ${{ steps.meta.output.labels }}
